[package]

name = "rustless"
version = "0.0.1"
authors = ["Tuomas Tynkkynen <tuomas.tynkkynen@iki.fi>"]

[[bin]]
name = "rl"

[dependencies.libtermutils]
git = "https://github.com/dezgeg/rust-term.git"
